PaddlePaddle/PaddleFL

docs/source/md/quick_start.md
paddle_fl/version.py
setup.py

add paddlepaddle as install requirement and update paddle-fl version

add paddlepaddle as install requirement

---

paddle_fl/__init__.py
paddle_fl/core/master/__init__.py
paddle_fl/core/master/fl_job.py
paddle_fl/core/master/job_generator.py
paddle_fl/core/scheduler/agent_master.py
paddle_fl/core/server/fl_server.py
paddle_fl/core/strategy/fl_distribute_transpiler.py
paddle_fl/core/strategy/fl_strategy_base.py
paddle_fl/core/trainer/diffiehellman/__init__.py
paddle_fl/core/trainer/diffiehellman/diffiehellman.py
paddle_fl/core/trainer/diffiehellman/exceptions.py
paddle_fl/core/trainer/fl_trainer.py
paddle_fl/examples/ctr_demo/fl_master.py
paddle_fl/examples/ctr_demo/fl_trainer.py
paddle_fl/examples/dpsgd_demo/fl_master.py
paddle_fl/examples/dpsgd_demo/fl_trainer.py
paddle_fl/examples/gru4rec_demo/fl_trainer.py
paddle_fl/examples/secagg_demo/fl_master.py
paddle_fl/examples/secagg_demo/fl_trainer.py
setup.py

Indentation fixed

---

paddle_fl/core/strategy/fl_distribute_transpiler.py

resolve #27
Optimizer Adam has been verified in the example "gru4rec_demo".

modify fl_distribute_transpiler.py to support adam optimizer (resolve #27).

---

paddle_fl/core/trainer/fl_trainer.py
paddle_fl/dataset/femnist.py
paddle_fl/examples/femnist_demo/fl_master.py
paddle_fl/examples/femnist_demo/fl_trainer.py
paddle_fl/version.py

When running femnist example in single machine, data download and extraction may meet conflict issue. Fix the problem by putting data of different trainers into different folders.

fix dataset conflict issue in single machine simulation

---

docs/requirements.txt
docs/source/md/quick_start.md
paddle_fl/core/scheduler/agent_master.py
paddle_fl/core/trainer/diffiehellman/diffiehellman.py
paddle_fl/core/trainer/fl_trainer.py
paddle_fl/dataset/femnist.py
paddle_fl/examples/ctr_demo/fl_scheduler.py
paddle_fl/examples/ctr_demo/fl_server.py
paddle_fl/examples/ctr_demo/fl_trainer.py
paddle_fl/examples/dpsgd_demo/fl_scheduler.py
paddle_fl/examples/dpsgd_demo/fl_server.py
paddle_fl/examples/dpsgd_demo/fl_trainer.py
paddle_fl/examples/dpsgd_demo/run.sh
paddle_fl/examples/femnist_demo/fl_scheduler.py
paddle_fl/examples/femnist_demo/fl_server.py
paddle_fl/examples/femnist_demo/fl_trainer.py
paddle_fl/examples/femnist_demo/run.sh
paddle_fl/examples/gru4rec_demo/fl_scheduler.py
paddle_fl/examples/gru4rec_demo/fl_server.py
paddle_fl/examples/gru4rec_demo/fl_trainer.py
paddle_fl/examples/secagg_demo/fl_scheduler.py
paddle_fl/examples/secagg_demo/fl_server.py
paddle_fl/examples/secagg_demo/fl_trainer.py
paddle_fl/examples/secagg_demo/run.sh
paddle_fl/examples/submitter_demo/conf.txt
paddle_fl/examples/submitter_demo/kill.sh
paddle_fl/examples/submitter_demo/scheduler_client.py
paddle_fl/examples/submitter_demo/train_program.py
paddle_fl/version.py

Unify the variable names in examples and add more comments, to make examples more easy to follow.

Make examples more easy to follow

---

paddle_fl/examples/submitter_demo/scheduler_client.py
paddle_fl/examples/submitter_demo/train_program.py
paddle_fl/version.py
setup.py

fix bug in submitter:
different http server between python2 and python3
Unify variable names in submitter_demo

fix bug in submitter_demo:

---

README.md
README_cn.md
paddle_fl/examples/submitter_demo/conf.txt
paddle_fl/version.py

Document update

---

paddle_fl/core/trainer/fl_trainer.py
paddle_fl/examples/ctr_demo/fl_trainer.py
paddle_fl/examples/dpsgd_demo/fl_trainer.py
paddle_fl/examples/femnist_demo/fl_trainer.py
paddle_fl/examples/gru4rec_demo/fl_trainer.py
paddle_fl/examples/k8s_deployment/trainer0/fl_trainer.py
paddle_fl/examples/k8s_deployment/trainer1/fl_trainer.py
paddle_fl/examples/secagg_demo/fl_trainer.py
paddle_fl/examples/submitter_demo/train_program.py

- Fix the bug trainer.start() when assgining CUDAPlace()

fix bug in trainer start

---

core/paddlefl_mpc/operators/mpc_elementwise_add_op.h
python/paddle_fl/mpc/examples/uci_demo/uci_housing_demo.py
python/setup.py

- Add paddle_fl/version.py
- Fix bugs in elementwise_add_op

fix bugs in New version

---

python/paddle_fl/paddle_fl/core/master/job_generator.py
python/paddle_fl/paddle_fl/core/strategy/fl_distribute_transpiler.py
python/paddle_fl/paddle_fl/core/trainer/fl_trainer.py
python/paddle_fl/paddle_fl/examples/detection_demo/README.md
python/paddle_fl/paddle_fl/examples/detection_demo/download.sh
python/paddle_fl/paddle_fl/examples/detection_demo/fl_master.py
python/paddle_fl/paddle_fl/examples/detection_demo/fl_scheduler.py
python/paddle_fl/paddle_fl/examples/detection_demo/fl_server.py
python/paddle_fl/paddle_fl/examples/detection_demo/fl_trainer.py
python/paddle_fl/paddle_fl/examples/detection_demo/run.sh
python/paddle_fl/paddle_fl/examples/generate_job_from_program/fl_trainer.py
python/paddle_fl/paddle_fl/examples/generate_job_from_program/program_saver.py
python/version.py

- Add momentum optimizer
- Fix bug in save_program api
- Enable  warmup lr

update load program function and add detection demo

---

python/paddle_fl/paddle_fl/examples/ctr_demo/fl_trainer.py
python/paddle_fl/paddle_fl/examples/ctr_demo/run.sh

* update run.sh 
* limit the epoch to train in fl_trainer.py

Update ctr scripts

---

python/paddle_fl/mpc/examples/mnist_demo/process_data.py
python/paddle_fl/mpc/examples/uci_demo/README.md
python/paddle_fl/mpc/examples/uci_demo/README_CN.md
python/paddle_fl/mpc/examples/uci_demo/decrypt_save.py
python/paddle_fl/mpc/examples/uci_demo/prepare.py
python/paddle_fl/mpc/examples/uci_demo/process_data.py
python/paddle_fl/mpc/examples/uci_demo/run_standalone.sh
python/paddle_fl/mpc/examples/uci_demo/uci_housing_demo.py

* 添加数据生成文件 prepare.py
* 将解密操作从process_data.py单独拿出来
* 添加解密文件decrypt_save.py， 并支持传参来指定解密后loss 以及prediction文件存放路径
* 更新run_standlone.sh 文件
*  将PYTHON、REDIS_HOME、SERVER、PORT 从环境变量中获取
*  在运行前添加数据检查
* 更新uci_hosing_demo.py
*  增加batch_cost打印
*  fix epoch_cost 打印
* 对应更新中英文文档

Update mpc uci demo

---

python/paddle_fl/mpc/examples/mnist_demo/README.md
python/paddle_fl/mpc/examples/mnist_demo/README_CN.md
python/paddle_fl/mpc/examples/mnist_demo/decrypt_save.py
python/paddle_fl/mpc/examples/mnist_demo/mnist_demo.py
python/paddle_fl/mpc/examples/mnist_demo/prepare.py
python/paddle_fl/mpc/examples/mnist_demo/run_standalone.sh

* 添加数据生成文件 prepare.py
* 添加解密文件decrypt_save.py， 并支持传参来指定lable文件存放路径
* 更新run_standlone.sh 文件
*  将PYTHON、REDIS_HOME、SERVER、PORT 从环境变量中获取
*  在运行前添加数据检查
* 更新mnist_demo.py
*  增加batch_cost打印
*  fix epoch_cost 打印
* 对应更新中英文文档

Update mpc scripts

---

core/paddlefl_mpc/data_utils/data_utils.cc
core/paddlefl_mpc/operators/mpc_relu_op.cc
core/paddlefl_mpc/operators/mpc_relu_op.h
core/privc3/circuit_context.h
core/privc3/fixedpoint_tensor.h
core/privc3/fixedpoint_tensor_imp.h
core/privc3/fixedpoint_tensor_test.cc
python/paddle_fl/mpc/layers/ml.py
python/paddle_fl/mpc/mpc_layer_helper.py

fix conflict bugs.

---

python/paddle_fl/mpc/examples/lenet_with_mnist/train_lenet.py
python/paddle_fl/mpc/examples/linear_reg_with_uci/uci_demo.py
python/paddle_fl/mpc/examples/logistic_with_mnist/train_fc_softmax.py
python/paddle_fl/paddle_fl/examples/deploy_serving_after_training/run.sh

make_dist_auto in ce

---

contrib/data_safety_training/image_classification/server/server.py
core/paddlefl_mpc/operators/metrics/precision_recall_op.h
core/paddlefl_mpc/operators/mpc_gru_op.h
python/paddle_fl/mobile/clients/data_client_impl.py
python/paddle_fl/mobile/clients/scheduler_client_impl.py
python/paddle_fl/mobile/utils/hdfs_utils.py
python/paddle_fl/mpc/data_utils/op_extra_desc.py
python/paddle_fl/mpc/examples/fm_with_criteo/args.py
python/paddle_fl/mpc/examples/fm_with_criteo/dataset_generator.py
python/paddle_fl/mpc/examples/fm_with_criteo/evaluate_metrics.py
python/paddle_fl/mpc/examples/fm_with_criteo/load_model_and_infer.py
python/paddle_fl/mpc/examples/fm_with_criteo/mpc_network.py
python/paddle_fl/mpc/examples/fm_with_criteo/train_fm.py
python/paddle_fl/mpc/examples/lenet_with_mnist/train_lenet.py
python/paddle_fl/mpc/examples/linear_reg_with_uci/uci_demo.py
python/paddle_fl/mpc/examples/mean_normalize_demo/mean_normalize_demo.py
python/paddle_fl/mpc/examples/mean_normalize_demo/process_data.py
python/paddle_fl/mpc/examples/mean_normalize_demo/verify.py
python/paddle_fl/mpc/examples/model_decryption/decrypt_and_inference.py
python/paddle_fl/mpc/framework.py
python/paddle_fl/mpc/initializer.py
python/paddle_fl/mpc/layers/ml.py
python/paddle_fl/mpc/optimizer.py
python/paddle_fl/mpc/tests/unittests/test_op_conv.py
python/paddle_fl/paddle_fl/core/strategy/details/ps_dispatcher.py
python/setup.py

sync code with icode: improve codestyle.

sync code with icode.

---

python/paddle_fl/mpc/examples/youtubednn_with_movielens/README.md
python/paddle_fl/mpc/examples/youtubednn_with_movielens/README_CN.md
python/paddle_fl/mpc/examples/youtubednn_with_movielens/args.py
python/paddle_fl/mpc/examples/youtubednn_with_movielens/decrypt_and_evaluate.py
python/paddle_fl/mpc/examples/youtubednn_with_movielens/get_topk.py
python/paddle_fl/mpc/examples/youtubednn_with_movielens/mpc_network.py
python/paddle_fl/mpc/examples/youtubednn_with_movielens/process_data.py
python/paddle_fl/mpc/examples/youtubednn_with_movielens/train_youtubednn.py

add YoutubeDNN demo.

---

core/paddlefl_mpc/mpc_protocol/aby3_operators.h
core/paddlefl_mpc/mpc_protocol/mpc_operators.h
core/paddlefl_mpc/operators/mpc_reveal.cc
core/paddlefl_mpc/operators/mpc_reveal_op.h
core/paddlefl_mpc/operators/mpc_share_op.cc
core/paddlefl_mpc/operators/mpc_share_op.h
core/privc3/fixedpoint_tensor.h
core/privc3/fixedpoint_tensor_imp.h
python/paddle_fl/mpc/examples/linear_reg_with_uci/decrypt_save.py
python/paddle_fl/mpc/examples/linear_reg_with_uci/process_data.py
python/paddle_fl/mpc/examples/linear_reg_with_uci/uci_demo.py
python/paddle_fl/mpc/layers/basic.py

support online share.

---

python/paddle_fl/split_learning/README.md

- Creat split_learning category for split_learning source code

Creat split_learning for code submit

---

python/paddle_fl/split_learning/core/__init__.py
python/paddle_fl/split_learning/core/customer.py
python/paddle_fl/split_learning/core/host.py
python/paddle_fl/split_learning/core/proto/common.proto
python/paddle_fl/split_learning/core/proto/gen_code.py
python/paddle_fl/split_learning/core/reader/__init__.py
python/paddle_fl/split_learning/core/reader/default_reader.py
python/paddle_fl/split_learning/core/reader/reader_base.py
python/paddle_fl/split_learning/core/reformer.py
python/paddle_fl/split_learning/core/table/__init__.py
python/paddle_fl/split_learning/core/table/redis_table.py
python/paddle_fl/split_learning/core/table/table_base.py
python/paddle_fl/split_learning/core/util.py

add split learning

---

python/paddle_fl/split_learning/core/customer.py
python/paddle_fl/split_learning/core/host.py
python/paddle_fl/split_learning/core/proto/gen_code.py
python/paddle_fl/split_learning/core/table/redis_table.py
python/paddle_fl/split_learning/core/util.py
python/paddle_fl/split_learning/requirements.txt

add requment.txt
remove unused import

[split_learning] fix python requirements

---

python/paddle_fl/paddle_fl/core/trainer/fl_trainer.py

fix bug in data parallel

---

python/paddle_fl/paddle_fl/examples/k8s_deployment/master_v16up.yaml

add k8s deployment configure file for k8s version 1.16+

add k8s deployment configure file for k8s version 1.16+

---

README.md
README_cn.md
docs/source/md/compile_and_install.md
docs/source/md/compile_and_install_cn.md
docs/source/md/introduction.md
python/paddle_fl/mpc/examples/linear_reg_with_uci/decrypt_save.py
python/paddle_fl/mpc/examples/model_decryption/decrypt_and_inference.py

1. Update readme files.
2. Modify the compile_and_install instructions.
3. Correct several mistakes.

Update related files.

---

python/paddle_fl/mpc/examples/youtubednn_with_movielens/process_data.py
python/paddle_fl/mpc/examples/youtubednn_with_movielens/train_youtubednn.py

Fix problems in PaddleFL/python/paddle_fl/mpc/examples/youtubednn_with_movielens.
fixes #219

for_youtubednn

---

CMakeLists.txt
feature/he/CMakeLists.txt
feature/he/he_utils.cc
feature/he/paillier.cc
feature/he/paillier.h
feature/proto/metrics.proto
feature/proto/run_protogen.py
feature/python/__init__.py
feature/python/core/__init__.py
feature/python/core/federal_feature_engineering_client.py
feature/python/core/federal_feature_engineering_server.py
feature/python/core/metrics_client.py
feature/python/core/metrics_server.py
feature/python/example/README.md
feature/python/example/__init__.py
feature/python/example/gen_test_file.py
feature/python/example/metrics_plain.py
feature/python/example/metrics_test_client.py
feature/python/example/metrics_test_server.py

Federal feature engineering, support postive_ratio, woe, iv.

add positive_ratio,woe,iv

---

core/he/he_utils.cc
python/paddle_fl/feature_engineering/core/federated_feature_engineering_client.py
python/paddle_fl/feature_engineering/core/federated_feature_engineering_server.py
python/paddle_fl/feature_engineering/core/metrics_client.py
python/paddle_fl/feature_engineering/core/metrics_server.py
python/paddle_fl/feature_engineering/example/metrics_plain.py
python/paddle_fl/feature_engineering/example/metrics_test_client.py
python/paddle_fl/feature_engineering/example/metrics_test_server.py
python/paddle_fl/feature_engineering/proto/metrics.proto

add ks,auc

---

python/paddle_fl/__init__.py
python/paddle_fl/feature_engineering/README.md
python/setup.py

support compilation with paddlefl

add feature engineering submodule

---

python/paddle_fl/feature_engineering/README.md
python/paddle_fl/feature_engineering/core/federated_feature_engineering_client.py
python/paddle_fl/feature_engineering/core/federated_feature_engineering_server.py
python/paddle_fl/feature_engineering/core/metrics_client.py
python/paddle_fl/feature_engineering/core/metrics_server.py
python/paddle_fl/feature_engineering/example/metrics_test_client.py
python/paddle_fl/feature_engineering/proto/metrics.proto

add log for feature engineering;
update README

add log for feature engineering

---

python/paddle_fl/feature_engineering/README.md
python/paddle_fl/feature_engineering/core/metrics_server.py
python/paddle_fl/feature_engineering/example/gen_test_file.py
python/paddle_fl/feature_engineering/example/metrics_plain.py
python/paddle_fl/feature_engineering/example/metrics_test_client.py
python/paddle_fl/feature_engineering/example/metrics_test_server.py

fix auc,ks bug
